-v doesn't allow you to set version
StackStorm/st2-packages pull request #665
Opened 2020-10-09 11:13 UTC by amanda11

The install.sh supports -v and --version to set the version.

Using --version=3.2.0 then it allows you to configure the specify the version to install.

However if you use -v=3.2.0 or -v3.2.0 then it ignores the version specified and uses the default value set to BRANCH. If you use "-v 3.2.0" then it complains that the version -v is not valid.

I believe that you should have been able to use -v=3.2.0 or --version=3.2.0 - and have amended the setup_args so that it will extract the version number out on -v same as --version.

NB. This appears to be legacy behaviour, so should not be a blocker for 3.3 release.

2020-10-23 17:04 UTC, m4dcoder requested changes
@amanda11 This is a good catch. Can you also update https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.sh#L35 and other el7/el8 scripts? There are also the template that generated those script files at https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.template.sh#L27. The main script probably just pass `--version` but we should fix the other scripts just in case.  I think you should update the deb/el7/el8 templates and then regenerate the deb/el7/el8 scripts. Thanks!

2020-10-29 17:18 UTC, amanda11 commented
> @amanda11 This is a good catch. Can you also update https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.sh#L35 and other el7/el8 scripts? There are also the template that generated those script files at https://github.com/StackStorm/st2-packages/blob/master/scripts/st2bootstrap-deb.template.sh#L27. The main script probably just pass `--version` but we should fix the other scripts just in case.  I think you should update the deb/el7/el8 templates and then regenerate the deb/el7/el8 scripts. Thanks!

Thanks @m4dcoder for the review - I have updated the extra files, ready for your re-review whenever you have time.

2020-10-29 21:03 UTC, blag approved these changes
LGTM

2020-11-06 18:02 UTC, m4dcoder approved these changes

2020-11-06 18:19 UTC, merged